### ISSUE TITLE
Integrate watcher into CI for GS

### ISSUE THREAD

**Issue by TT-billteng** [tenstorrent-metal/tt-metal#2134]
Issues that watcher has uncovered from our post_commit suite: 

Hang:

- [x] #4151 

Watcher noc transaction errors / immediately actionable: 

- [x] #3827 
- [x] #3988 
- [x] #4069

PCC errors

- [x] #4055
- [x] #4086 - testing [here](https://github.com/tenstorrent-metal/tt-metal/actions/runs/7094906615)
- [x] #4089 - David has fixed, currently testing [here](https://github.com/tenstorrent-metal/tt-metal/actions/runs/7091168624)
- [x] #3625 - to remain disabled on Bill's branch. this test will be deprecated soon.
- [x] #4085 - Muthu to check PCC 
- [x] #4088 - Muthu to check PCC; not passing stress test https://github.com/tenstorrent-metal/tt-metal/actions/runs/7084274248/job/19278233730

**Comment by jliangTT** [comment]
@TT-billteng , what is the status of the remaining issues here? do we know if they still fail with these test turned on?

**Comment by TT-billteng** [comment]
Watcher is now active on the stress test pipeline and recently has been green! https://github.com/tenstorrent-metal/tt-metal/actions/runs/7441497962
