### ISSUE TITLE
[On Hold] Make e2e Demo for 5 functional models

### ISSUE THREAD

**Issue by boris-drazic** [tenstorrent-metal/tt-metal#4466]
For 3 models implemented with `ttnn` make end2end demo files.
These models are
- [x] functional_bert **[Sudharsan]** [PR #4582](https://github.com/tenstorrent-metal/tt-metal/pull/4582) [Merged]
- [x] functional_bloom **[Punith]** [PR #4554](https://github.com/tenstorrent-metal/tt-metal/pull/4554) [Merged]
- [x] functional_t5 **[Vignesh]** [PR #4649](https://github.com/tenstorrent-metal/tt-metal/pull/4649) [Merged]

For each model make a demo folder and add `py` and readme file like in `models/demos/metal_BERT_large_11`

**Comment by davorchap** [comment]
fyi @jliangTT

**Comment by Sudharsan-V** [comment]
After creating a demo for functional_bert, functional_bloom, and functional_t5. Create e2e demo for functional_whisper model

**Comment by Sudharsan-V** [comment]
Please find the independent tickets/issues for the models below:
functional_bloom : [#4503](https://github.com/tenstorrent-metal/tt-metal/issues/4503)
functional_t5 : [#4504](https://github.com/tenstorrent-metal/tt-metal/issues/4504)
functional_bert : [#4505](https://github.com/tenstorrent-metal/tt-metal/issues/4505)

**Comment by saichandax** [comment]
Currently, only 2 models are pending at different levels.
- [x] functional_bert **[Sudharsan]** [PR #4582](https://github.com/tenstorrent-metal/tt-metal/pull/4582) [Review needed]
- [ ] functional_whisper **[Vignesh]** [WIP]

The work will be resumed after Stable Diffusion tasks are done #4765

**Comment by boris-drazic** [comment]
Functional whisper implementation is a separate task now.
