### ISSUE TITLE
Llama2-70B bringup

### ISSUE THREAD

**Issue by cglagovich** [tenstorrent-metal/tt-metal#5151]
High level issue tracking Llama2-70B bringup.

### Tasks:
Functional single layer on single chip WH
- [x] MLP
- [x] QKV proj
- [x] Reshape heads & Rotary Emb
- [x] KV cache update and unpad
- [x] Attn matmuls and softmax
- [x] Decoder
- [x] Model

Emulate sharding on single chip
- [x] MLP
- [x] Attention
- [x] Decoder
- [x] Model

T3000 4-chip scale-up
- [x] AllGather test passing
- [x] Fractured MLP passing
- [x] Fractured Attention passing
- [x] Fractured Decoder passing
- [x] Fractured Model passing
